# Generated by Django 5.0.1 on 2024-01-11 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалено'), ('formed', 'Сформировано'), ('completed', 'Добавлено'), ('rejected', 'Отклонено')], default='draft', max_length=16)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('formation_date', models.DateField(default=None, null=True)),
                ('completion_date', models.DateField(default=None, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('open_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('image_url', models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Wetterstation01.jpeg/330px-Wetterstation01.jpeg', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StationsMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeStatsAPI.measurement')),
                ('weather_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeStatsAPI.weatherstation')),
            ],
        ),
        migrations.CreateModel(
            name='WeStatsUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('groups', models.ManyToManyField(related_name='we_stats_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='we_stats_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_measurements', to='WeStatsAPI.westatsuser'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_measurements', to='WeStatsAPI.westatsuser'),
        ),
    ]
