# Generated by Django 5.0.1 on 2024-01-13 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeStatsAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='formation_date',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='status',
        ),
        migrations.AddField(
            model_name='measurement',
            name='weather_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WeStatsAPI.weatherstation'),
        ),
        migrations.CreateModel(
            name='MeasurementOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалено'), ('formed', 'Сформировано'), ('completed', 'Добавлено'), ('rejected', 'Отклонено')], default='draft', max_length=16)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('formation_date', models.DateField(default=None, null=True)),
                ('completion_date', models.DateField(default=None, null=True)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_order', to=settings.AUTH_USER_MODEL)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeStatsAPI.measurement')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
