# Generated by Django 5.0.1 on 2024-01-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeStatsAPI', '0004_measurementorderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeasurementOrder',
            new_name='OrderInfo',
        ),
        migrations.RenameModel(
            old_name='MeasurementOrderItem',
            new_name='OrderItemMeasurement',
        ),
    ]
