# Generated by Django 5.0.1 on 2024-01-15 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeStatsAPI', '0005_rename_measurementorder_orderinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='completion_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='formation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
