# Generated by Django 5.0.1 on 2024-01-15 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeStatsAPI', '0006_alter_orderinfo_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='westatsuser',
            name='user_role',
            field=models.CharField(choices=[('just_user', 'Пользователь'), ('meteorologist', 'Метеоролог'), ('r_manager', 'Менеджер'), ('r_admin', 'Админ')], default='just_user', max_length=16, verbose_name='Роль пользователя'),
        ),
    ]
