# Generated by Django 5.0.1 on 2024-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeStatsAPI', '0007_alter_measurement_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='westatsuser',
            name='name',
            field=models.CharField(default='Noname', max_length=50, verbose_name='Имя'),
        ),
    ]
