# Generated by Django 5.0 on 2023-12-16 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('visitor', 'Посетитель'), ('meteoUser', 'Метеоролог'), ('moder', 'Модератор')], default='visitor', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStations',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('opendate', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('image_url', models.CharField(default='no_image.png', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалено'), ('formed', 'Сформировано'), ('completed', 'Добавлено'), ('rejected', 'Отклонено')], default='draft', max_length=16)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('formation_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_measurements', to='Lab03_API.user')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_measurements', to='Lab03_API.user')),
            ],
        ),
        migrations.CreateModel(
            name='StationsMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab03_API.measurements')),
                ('weatherStations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab03_API.weatherstations')),
            ],
        ),
    ]
